# No mostrar la línea nueva al principio
add_newline = false

# Un formato simple y limpio
format = "$directory$git_branch$git_status$character"

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
symbol = " "
style = "bright-black"
